[theme]
base = "light"
primaryColor = "#b91c1c"
backgroundColor = "#ede4d0"
secondaryBackgroundColor = "#faf6eb"
textColor = "#171412"
font = "serif"

[browser]
gatherUsageStats = false

[server]
runOnSave = true
